_meta_:
    input_root: 'aaa'
    output_root: 'aaa/e'
    recursively: True  # recursively folder detecting
    folder_list: ["a", "b", "c", "d"]  # if assigned, only selected folders will be handled
    # save_format: '.jpg'

combination:
    axis: 'x'  # 'x', 'y' or 'xy'(combine all inputs into one output image)
    one_folder_axis: 'x'  # only set when axis = 'xy'
    tiles:
        w: 2  # num_a_row
        h: 2  # rows(folders)
#    image_size:
#        w: 400
#        h: 337
#    gap:
#        dw: 15
#        dh: 15



