#__meta__:
#    input_root: 'raw'
#    compare_root: ''
#    output_root: 'trans'
#    recursively: True  # include sub directory
#    # folder_list: ["12", "4", "29", "94", "96"]  # if assigned, only selected folders will be handled
#    # save_format: '.jpg'


workflow:
    - op1:
        __meta__:
            input: 'trans'
            output: 'combine'
            recursively: True  # recursively = True: include sub directory

        combine:
            one_folder_in_axis: 'xy'        # x/y or xy
            priority_axis: 'x'
            tiles:                          # if combine each folder into one image, tiles must be specified.
                x: 10 # num_a_row
                y: 10  # rows(folders)
#            image_size:
#                w: 400
#                h: 337
#            gap:
#                dw: 15
#                dh: 15
#            combine_size:                   # overlap mode
#                w: 1024
#                h: 1024

