crop:
    enable: False
    size:
        w: 400
        h: 400
resize:
    enable: True
    size:
        w: 400
        h: 400
flip:
    vertical: False
    horizontal: False

rotate:
    enable: False
    angle: 90   # clockwise

combination:
    folder_path: "auto"  # auto or manual
    folder: ['a', 'b', 'c', 'd']  # only works in manual mode
    tiles:
        w: 8  # num_a_row
        h: 5  # rows(folders)
    image_size:
        w: 400
        h: 337
    gap:
        dw: 15
        dh: 15
    input_dir: 'raw'
    output: 'combine.png'
split:

comparison_annotation:
    folder_path: "manual"  # auto or manual
    mode: "compare"  # compare or crop
    folder: ["12", "4", "29", "94", "96"]  # only works in manual mode
    annotations: [1, 2, 1, 2, 1]
    color:
        - ['green']
        - ['green', 'wheat']
        - ['red']
        - ['red', 'green']
        - ['blue']
    thickness: 5
    input_dir: 'raw'
    output_folder: 'compare'


