_meta_:
    input_root: 'val'
    compare_root: ''
    output_root: 'val_crop'
    recursively: True  # recursively folder detecting
    # folder_list: ["12", "4", "29", "94", "96"]  # if assigned, only selected folders will be handled
    # save_format: '.jpg'
    mode: '1_to_n'

crop:
    tiles:
        w: 4
        h: 4
