# General Structure
################################################################################
# workflow:
#     - op1:  # can be any name you like
#         __meta__:
#             input: 'val'
#             output: 'split'
#             recursively: False  # recursively = True: include sub directory
#             # folder_list: ["12", "4", "29", "94", "96"] 
#         split:  # what operation
#             tiles:  # operation configs
#                 w: 2
#                 h: 2
#
#     - op2:  # next op
#         __meta__:
#             ....
################################################################################

# All ops template

workflow:
    - template:
        __meta__:
            input: 'input'
            compare: 'compare'
            output: 'output'

        combine:
            one_folder_in_axis: 'xy'
            priority_axis: 'x'
            tiles:
                w: 2  # num_a_row
                h: 2  # rows(folders)
        split:
            tiles:
                w: 4
                h: 4

        evaluate:
            - f1
            - f2
            - ssim

        transformation:
            - copy:
                save: '_1'
            - rotate:
                - 90
                - 90
                - 90:
                    save: '_270'
            - flip:
                - vertical:
                    save: '_v.tiff'
                - horizontal:
                    save: '_vh.jpg'
                - both

            - resize:
                w: 200
                h: 200
                save: '_200.png'

            - fix_crop:
                from:
                    left: 0
                    top: 0
                size:
                    w: 200
                    h: 200
                save: '_crop'

            - random_crop:
                size:
                    w: 256
                    h: 256
                patches: 100
                save: '_crop.tiff'



