# General Structure
################################################################################
# workflow:
#     - op1:  # can be any name you like
#         __meta__:
#             input: 'val'
#             output: 'split'
#             recursively: False  # recursively = True: include sub directory
#             # folder_list: ["12", "4", "29", "94", "96"] 
#         split:  # what operation
#             tiles:  # operation configs
#                 w: 2
#                 h: 2
#
#     - op2:  # next op
#         __meta__:
#             ....
################################################################################

# All ops template

workflow:
    - template_op1:
        __meta__:
            input: 'input'
            compare: 'compare'
            output: 'output'
            recursively: True  # include sub directory
            # folder_list: ["12", "4", "29", "94", "96"]  # if assigned, only selected folders will be handled

        #################
        #    Combine
        #################
        combine:
            one_folder_in_axis: 'xy'        # `x`/`y` or `xy`
            priority_axis: 'x'
            tiles:                          # if combine each folder into one image (`xy` axis), tiles must be specified.
                w: 2 # num_a_row
                h: 2  # rows(folders)
            image_size:
                w: 400
                h: 337
            gap:
                dw: 15
                dh: 15

        #################
        #     Split
        #################
        split:
            tiles:
                w: 4
                h: 4

        #################
        #    Evaluate
        #################
        evaluate:
            - f1
            - f2
            - ssim
            - psnr

        #################
        # Transformation
        #################
        transformation:
            - copy:
                save: '_1'
            - rotate:
                - 90
                - 90
                - 90:
                    save: '_270'
            - flip:
                - vertical:
                    save: '_v.tiff'
                - horizontal:
                    save: '_vh.jpg'
                - both

            - resize:
                w: 200
                h: 200
                save: '_200.png'

            - fix_crop:
                from:
                    left: 0
                    top: 0
                size:
                    w: 200
                    h: 200
                save: '_crop'

            - random_crop:
                size:
                    w: 256
                    h: 256
                patches: 100
                save: '_crop.tiff'

            - overlap_crop:
                size:
                    w: 256
                    h: 256
                patches:
                    x: 10
                    y: 10
                save: '_crop.tiff'



