#__meta__:
#    input_root: 'raw'
#    compare_root: ''
#    output_root: 'trans'
#    recursively: True  # include sub directory
#    # folder_list: ["12", "4", "29", "94", "96"]  # if assigned, only selected folders will be handled
#    # save_format: '.jpg'


workflow:
    - op1:
        __meta__:
            input: 'val'
            output: 'trans'
            recursively: True  # recursively = True: include sub directory

        transformation:
            - random_crop:
                size:
                    w: 256
                    h: 256
                patches: 100
                save: '_crop.tiff'


#    - op1:
#        __meta__:
#            input: 'input'
#            output: 'output'
#            recursively: True  # recursively = True: include sub directory
#        transformation:
#            - rotate:
#                - 90:
#                    save: '_90.png'
#                - 180:
#                    save: '_270.png'


#        split:
#            tiles:
#                w: 4
#                h: 4
#        transformation:
#            - copy:
#                save: ''

#            - binary:
#                thresh: 175
#                save: '.tiff'

#            - rotate:
#                - 90
#                - 90
#                - 90:
#                    save: '_270'
#            - flip:
#                - vertical:
#                    save: '_v.tiff'
#                - horizontal:
#                    save: '_vh.jpg'
#                - both

#            - resize:
#                w: 200
#                h: 200
#                save: '_200.png'

#            - fix_crop:
#                from:
#                    left: 0
#                    top: 0
#                size:
#                    w: 200
#                    h: 200
#                save: '_crop'
#
#            - random_crop:
#                size:
#                    w: 256
#                    h: 256
#                patches: 100
#                save: '_crop.tiff'


