_meta_:
    input_root: 'raw'
    compare_root: ''
    output_root: 'trans'
    recursively: True  # recursively folder detecting
    # folder_list: ["12", "4", "29", "94", "96"]  # if assigned, only selected folders will be handled
    # save_format: '.jpg'

resize:
    w: 400
    h: 400
    # save: '_resize'

crop:
    mode: "fix"  # random or fix
    times:
        10  # only works in random mode
    start_point:   # only works in fix mode
        left: 0
        top: 0
    size:
        w: 200
        h: 200
flip:
    vertical: 'v'  # save suffix, empty for not saving
    horizontal: 'h'
    both: 'vh'

rotate:  # clockwise
    90: '90'  # save suffix, empty for not saving
    180: '180'
    270: '270'


