#_meta_:
#    input_root: 'raw'
#    compare_root: ''
#    output_root: 'trans'
#    recursively: True  # include sub directory
#    # folder_list: ["12", "4", "29", "94", "96"]  # if assigned, only selected folders will be handled
#    # save_format: '.jpg'


workflow:
    - op1:
        __meta__:
            input: 'val'
            output: 'copy'
            recursively: False  # recursively = True: include sub directory
        split:
            tiles:
                w: 4
                h: 4

    - op2:
        __meta__:
            input: 'copy'
            output: 'combine'
            recursively: True  # recursively = True: include sub directory
        combine:
            one_folder_in_axis: 'xy'
            priority_axis: 'x'
            tiles:
                w: 4  # num_a_row
                h: 4  # rows(folders)

    - op3:
          __meta__:
              input: 'cmp1'
              compare: 'cmp2'

          evaluate:
              - f1
              - f2
              - psnr
              - ssim


#        split:
#            tiles:
#                w: 4
#                h: 4
#        transformation:
#            - copy:
#                save: ''
#            - rotate:
#                - 90
#                - 90
#                - 90:
#                    save: '_270'
#            - flip:
#                - vertical:
#                    save: '_v.tiff'
#                - horizontal:
#                    save: '_vh.jpg'
#                - both
#            - resize:
#                w: 200
#                h: 200
#                save: '_200.png'
#            - fix_crop:
#                from:
#                    left: 0
#                    top: 0
#                size:
#                    w: 200
#                    h: 200
#                save: '_crop'

